# Generated by Django 4.0 on 2021-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_sport', models.CharField(max_length=25)),
                ('Dress_code', models.CharField(max_length=25)),
                ('Cost_for_equipment', models.IntegerField(max_length=100)),
                ('Played_this_sport', models.BooleanField(default=True)),
            ],
        ),
    ]
