# Generated by Django 4.0 on 2021-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Cost_for_equipment',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
