# Generated by Django 4.0 on 2021-12-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_alter_choice_cost_for_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Cost_for_equipment',
            field=models.IntegerField(default=100),
        ),
    ]
