# Generated by Django 4.0 on 2021-12-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_alter_choice_cost_for_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
    ]
