# Generated by Django 4.0 on 2021-12-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_rename_choice_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_of_player', models.CharField(max_length=25)),
                ('Name_of_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.choices')),
            ],
        ),
    ]
