# Generated by Django 4.0 on 2021-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_playereligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playereligibility',
            old_name='Name_of_player',
            new_name='player_belong_to',
        ),
        migrations.AddField(
            model_name='playereligibility',
            name='Name_of_player_id',
            field=models.CharField(default='temp', max_length=25),
        ),
    ]
