# Generated by Django 4.0 on 2021-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_rename_name_of_player_playereligibility_player_belong_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playereligibility',
            name='Name_of_player_id',
            field=models.CharField(max_length=25),
        ),
    ]
